<a href="https://colab.research.google.com/github/Gopichandkollu/Python-with-ML/blob/main/Day_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df=sns.load_dataset('taxis')
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pickup           6433 non-null   datetime64[ns]
 1   dropoff          6433 non-null   datetime64[ns]
 2   passengers       6433 non-null   int64
 3   distance         6433 non-null   float64
 4   fare             6433 non-null   float64
 5   tip              6433 non-null   float64
 6   tolls            6433 non-null   float64
 7   total            6433 non-null   float64
 8   color            6433 non-null   object
 9   payment          6389 non-null   object
 10  pickup_zone      6407 non-null   object
 11  dropoff_zone     6388 non-null   object
 12  pickup_borough   6407 non-null   object
 13  dropoff_borough  6388 non-null   object
dtypes: datetime64[ns](2), float64(5), int64(1), object(6)
memory usage: 703.7+ KB

In [4]:
df.sample(10)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
6171,2019-03-22 23:56:44,2019-03-23 00:22:53,1,6.88,23.0,0.00,0.00,24.30,green,cash,East Harlem South,Bedford Park,Manhattan,Bronx
575,2019-03-21 04:38:06,2019-03-21 04:56:45,2,7.40,23.5,5.45,0.00,32.75,yellow,credit card,Lower East Side,Manhattan Valley,Manhattan,Manhattan
5406,2019-03-16 22:38:08,2019-03-16 22:53:22,6,3.54,13.5,3.46,0.00,20.76,yellow,credit card,Times Sq/Theatre District,Manhattan Valley,Manhattan,Manhattan
6257,2019-03-22 20:14:33,2019-03-22 20:23:51,2,1.65,8.0,1.86,0.00,11.16,green,credit card,Elmhurst,Middle Village,Queens,Queens
1914,2019-03-25 16:09:02,2019-03-25 17:02:37,1,18.51,52.0,9.83,5.76,75.39,yellow,credit card,JFK Airport,West Village,Queens,Manhattan
4982,2019-03-12 15:17:52,2019-03-12 15:28:18,2,1.58,8.5,0.00,0.00,11.80,yellow,cash,Clinton East,Midtown North,Manhattan,Manhattan
5930,2019-03-04 21:16:10,2019-03-04 21:29:01,1,2.85,12.0,3.32,0.00,16.62,green,credit card,Elmhurst/Maspeth,Forest Hills,Queens,Queens
454,2019-03-08 18:37:06,2019-03-08 18:44:08,1,1.20,7.0,1.75,0.00,10.55,yellow,credit card,Morningside Heights,Upper West Side North,Manhattan,Manhattan
1301,2019-03-29 18:03:52,2019-03-29 18:27:36,1,3.22,16.5,0.00,0.00,20.80,yellow,cash,Yorkville West,Gramercy,Manhattan,Manhattan
4713,2019-03-30 11:25:43,2019-03-30 11:53:11,1,3.40,18.0,4.26,0.00,25.56,yellow,credit card,Clinton East,Lower East Side,Manhattan,Manhattan

In [5]:
df.head(15)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:37:23,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,12.96,yellow,credit card,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:07:31,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,18.80,yellow,credit card,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
7,2019-03-22 12:47:13,2019-03-22 12:58:17,0,1.40,8.5,0.00,0.0,11.80,yellow,NaN,Murray Hill,Flatiron,Manhattan,Manhattan
8,2019-03-23 11:48:50,2019-03-23 12:06:14,1,3.63,15.0,1.00,0.0,19.30,yellow,credit card,East Harlem South,Midtown Center,Manhattan,Manhattan
9,2019-03-08 16:18:37,2019-03-08 16:26:57,1,1.52,8.0,1.00,0.0,13.30,yellow,credit card,Lincoln Square East,Central Park,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.0,0.00,0.0,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
11,2019-03-20 19:39:42,2019-03-20 19:45:36,1,1.53,6.5,2.16,0.0,12.96,yellow,credit card,Upper West Side South,Manhattan Valley,Manhattan,Manhattan
12,2019-03-18 21:27:14,2019-03-18 21:34:16,1,1.05,6.5,1.00,0.0,11.30,yellow,credit card,Murray Hill,Midtown Center,Manhattan,Manhattan
13,2019-03-19 07:55:25,2019-03-19 08:09:17,1,1.75,10.5,0.00,0.0,13.80,yellow,cash,Lincoln Square West,Times Sq/Theatre District,Manhattan,Manhattan
14,2019-03-27 12:13:34,2019-03-27 12:25:48,0,2.90,11.5,0.00,0.0,14.80,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan

In [6]:
df.tail(10)

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
6423,2019-03-12 08:10:47,2019-03-12 08:35:35,1,4.30,18.50,0.00,0.0,19.30,green,credit card,Saint Albans,Hillcrest/Pomonok,Queens,Queens
6424,2019-03-30 20:52:15,2019-03-30 20:59:55,1,1.70,8.00,0.00,0.0,9.30,green,cash,Central Harlem,Central Harlem North,Manhattan,Manhattan
6425,2019-03-07 15:34:30,2019-03-07 16:31:06,1,9.12,26.32,0.00,0.0,26.82,green,credit card,Park Slope,East New York,Brooklyn,Brooklyn
6426,2019-03-28 08:04:47,2019-03-28 08:07:46,1,0.71,4.50,0.50,0.0,5.80,green,credit card,Central Park,Upper West Side North,Manhattan,Manhattan
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.00,0.00,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.50,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.00,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.00,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.00,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.00,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [7]:
df['color'].isnull()

0       False
1       False
2       False
3       False
4       False
        ...
6428    False
6429    False
6430    False
6431    False
6432    False
Name: color, Length: 6433, dtype: bool

In [8]:
df['color'].isnull().sum()

0

In [9]:
df['payment'].isnull().sum()

44

In [10]:
df.shape[0]

6433

In [11]:
(df.isnull().sum()/df.shape[0])*100

pickup             0.000000
dropoff            0.000000
passengers         0.000000
distance           0.000000
fare               0.000000
tip                0.000000
tolls              0.000000
total              0.000000
color              0.000000
payment            0.683973
pickup_zone        0.404166
dropoff_zone       0.699518
pickup_borough     0.404166
dropoff_borough    0.699518
dtype: float64

missing data handling
1) Imputation (fill in the blanks)
    1) stastical measures
    2) parameter domain

2) delete data
    rows
    columns

In [12]:
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [13]:
df.drop(['pickup','color','payment','total'],axis=1,inplace=True)

In [14]:
df

,dropoff,passengers,distance,fare,tip,tolls,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [15]:
df.drop([2,3,6430,6432],axis=0,inplace=True)

In [16]:
df

,dropoff,passengers,distance,fare,tip,tolls,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,Upper West Side South,Upper West Side South,Manhattan,Manhattan
4,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,Midtown East,Yorkville West,Manhattan,Manhattan
5,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
6,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...
6426,2019-03-28 08:07:46,1,0.71,4.5,0.50,0.0,Central Park,Upper West Side North,Manhattan,Manhattan
6427,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.0,Parkchester,East Harlem South,Bronx,Manhattan
6428,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6431,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn

In [17]:
df.reset_index()

,index,dropoff,passengers,distance,fare,tip,tolls,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,0,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,1,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,4,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,Midtown East,Yorkville West,Manhattan,Manhattan
3,5,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
4,6,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...
6424,6426,2019-03-28 08:07:46,1,0.71,4.5,0.50,0.0,Central Park,Upper West Side North,Manhattan,Manhattan
6425,6427,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.0,Parkchester,East Harlem South,Bronx,Manhattan
6426,6428,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,East Harlem North,Central Harlem North,Manhattan,Manhattan
6427,6429,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6428,6431,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn

In [18]:
df.reset_index(drop=True,inplace=True) # its mandatory to apply reset_index after deleting

In [19]:
df

,dropoff,passengers,distance,fare,tip,tolls,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,Midtown East,Yorkville West,Manhattan,Manhattan
3,2019-03-11 10:47:31,1,0.49,7.5,2.16,0.0,Times Sq/Theatre District,Midtown East,Manhattan,Manhattan
4,2019-03-26 21:17:29,1,3.65,13.0,2.00,0.0,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...
6424,2019-03-28 08:07:46,1,0.71,4.5,0.50,0.0,Central Park,Upper West Side North,Manhattan,Manhattan
6425,2019-03-23 18:49:12,1,7.07,20.0,0.00,0.0,Parkchester,East Harlem South,Bronx,Manhattan
6426,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,East Harlem North,Central Harlem North,Manhattan,Manhattan
6427,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6428,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn

In [20]:
df=sns.load_dataset('taxis')
df

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6428,2019-03-31 09:51:53,2019-03-31 09:55:27,1,0.75,4.5,1.06,0.0,6.36,green,credit card,East Harlem North,Central Harlem North,Manhattan,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.0,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.0,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6431,2019-03-04 10:09:25,2019-03-04 10:14:29,1,1.12,6.0,0.00,0.0,6.80,green,credit card,East New York,East Flatbush/Remsen Village,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.0,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [21]:
df[df['color']=='yellow']

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5446,2019-03-11 21:19:42,2019-03-11 21:29:23,1,2.09,9.5,2.66,0.0,15.96,yellow,credit card,Battery Park City,Financial District North,Manhattan,Manhattan
5447,2019-03-20 18:09:46,2019-03-20 18:16:52,1,1.52,7.5,2.36,0.0,14.16,yellow,credit card,Upper West Side South,Upper East Side North,Manhattan,Manhattan
5448,2019-03-09 11:08:09,2019-03-09 11:18:03,1,2.05,9.5,2.56,0.0,15.36,yellow,credit card,Lenox Hill West,Upper West Side South,Manhattan,Manhattan
5449,2019-03-22 18:12:50,2019-03-22 18:22:05,1,1.07,7.5,2.36,0.0,14.16,yellow,credit card,West Village,Penn Station/Madison Sq West,Manhattan,Manhattan
5450,2019-03-07 18:02:33,2019-03-07 18:13:32,1,1.80,9.0,1.33,0.0,14.63,yellow,credit card,Lincoln Square East,Upper West Side North,Manhattan,Manhattan

In [22]:
df['color']=='yellow'

0        True
1        True
2        True
3        True
4        True
        ...
6428    False
6429    False
6430    False
6431    False
6432    False
Name: color, Length: 6433, dtype: bool

In [23]:
total15=df[df['total']>15]
total15

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.00,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
6,2019-03-26 21:07:31,2019-03-26 21:17:29,1,3.65,13.00,2.00,0.0,18.80,yellow,credit card,Battery Park City,Two Bridges/Seward Park,Manhattan,Manhattan
8,2019-03-23 11:48:50,2019-03-23 12:06:14,1,3.63,15.00,1.00,0.0,19.30,yellow,credit card,East Harlem South,Midtown Center,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.00,0.00,0.0,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
15,2019-03-16 17:53:34,2019-03-16 18:13:57,3,2.09,13.50,0.00,0.0,16.80,yellow,cash,Upper West Side North,Clinton East,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6425,2019-03-07 15:34:30,2019-03-07 16:31:06,1,9.12,26.32,0.00,0.0,26.82,green,credit card,Park Slope,East New York,Brooklyn,Brooklyn
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.00,0.00,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.00,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.00,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.00,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn

In [24]:
type(total15)

pandas.core.frame.DataFrame

In [25]:
df[(df['payment']=='cash') | (df['total']>20)]

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.00,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.00,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
10,2019-03-16 10:02:25,2019-03-16 10:22:29,1,3.90,17.00,0.00,0.0,17.80,yellow,cash,LaGuardia Airport,Astoria,Queens,Queens
13,2019-03-19 07:55:25,2019-03-19 08:09:17,1,1.75,10.50,0.00,0.0,13.80,yellow,cash,Lincoln Square West,Times Sq/Theatre District,Manhattan,Manhattan
14,2019-03-27 12:13:34,2019-03-27 12:25:48,0,2.90,11.50,0.00,0.0,14.80,yellow,cash,Financial District North,Two Bridges/Seward Park,Manhattan,Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6425,2019-03-07 15:34:30,2019-03-07 16:31:06,1,9.12,26.32,0.00,0.0,26.82,green,credit card,Park Slope,East New York,Brooklyn,Brooklyn
6427,2019-03-23 18:26:09,2019-03-23 18:49:12,1,7.07,20.00,0.00,0.0,20.00,green,cash,Parkchester,East Harlem South,Bronx,Manhattan
6429,2019-03-31 17:38:00,2019-03-31 18:34:23,1,18.74,58.00,0.00,0.0,58.80,green,credit card,Jamaica,East Concourse/Concourse Village,Queens,Bronx
6430,2019-03-23 22:55:18,2019-03-23 23:14:25,1,4.14,16.00,0.00,0.0,17.30,green,cash,Crown Heights North,Bushwick North,Brooklyn,Brooklyn
6432,2019-03-13 19:31:22,2019-03-13 19:48:02,1,3.85,15.00,3.36,0.0,20.16,green,credit card,Boerum Hill,Windsor Terrace,Brooklyn,Brooklyn